### ISSUE TITLE
Vuetorrent Mod install

### ISSUE THREAD

**Issue by Aetherinox** [arafatamim/linuxserver-io-mod-vuetorrent#8]
I don't think this is an error with this theme, but I've googled for hours, and this error has plagued qbittorrent for awhile. As soon as I change the webui path to `/vuetorrent`, qbittorrent refreshes and I get:

```
Unacceptable file type, only regular file is allowed.
```

I can't possibly figure out what is going on here, because this should be a straight-forward thing. I added your mod to the docker-compose.yml file, restart, change the path, and it should work. But qbittorrent's error doesn't provide a bit of information which is frustrating.

**Comment by markmetcalfe** [comment]
I'm also experiencing the same issue, when setting the custom Web UI path to `/vuetorrent` on a fresh install of the `lscr.io/linuxserver/qbittorrent` image with `DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent` set.

**Comment by Aetherinox** [comment]
Yup. I did exactly that on both this image and the other one in the README.

It immediately would throw that error. I messed with it for 3 hours, messing with chown, permissions, re-creating the files 2-3 times.

Eventually, I gave up, mounted a new volume in my docker-compose.yml
```yml
    environment:
      UMASK: 022
      WEBUI_PORT: ${SERVICE_PORT_WEB}
      TORRENTING_PORT: ${SERVICE_PORT_TORRENT}
      TZ: Etc/UTC
    # DOCKER_MODS: arafatamim/linuxserver-io-mod-vuetorrent     <----- remove
    volumes:
      - ./torrents/downloads:/downloads
      - ./config:/config
      - ./vuetorrent:/vuetorrent                                <------ add
```

Then I manually downloaded the VueTorrent theme from their Github repo, and threw the folder `vuetorrent` in the root directory where the `docker-compose.yml` is.

```
📂 /path/to/docker/qbittorrent
   📂 config
   📂 torrents
   📂 vuetorrent
        📂 public
             📂 assets
                  📄 index.php
                  📄 images, etc
             📄 version.txt
   📄 docker-compose.yml
```

Then I removed the `DOCKER_MODS` variable, and started it up.

Go into the qb settings, enable WebUI, and set the path to `/vuetorrent`.

Vue WebUI works fine now, zero issues. Never got the error once.

If I were you, I'd just manually install Vue until one of these devs can figure out what's up.
